name: vietmap_flutter_gl
description: A Flutter map plugin for integrating Vietmap sdk inside a Flutter application, support for show a vector and raster map in Flutter. Supported on Android, iOS platforms .
version: 4.0.0-pre.2

homepage: https://maps.vietmap.vn
repository: https://github.com/vietmap-company/vietmap_flutter_gl
issue_tracker: https://github.com/vietmap-company/vietmap_flutter_gl/issues



environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter  
  supercluster: ^3.1.0
  turf: ^0.0.10
  vietmap_flutter_gl_web: 0.0.1-pre.3
  vietmap_gl_platform_interface: 1.0.0-pre.2
  

dev_dependencies:
  very_good_analysis: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: vn.vietmap.vietmapgl
        pluginClass: VietmapGLPlugin
      ios:
        pluginClass: MapLibreMapsPlugin
      web:
        default_package: vietmap_flutter_gl_web

platforms:
  android:
  ios:
  web:

topics:
  - vietmap
  - map
  - flutter-map
  - map-api


assets:
  - assets/center_pulse.png