blank_issues_enabled: false
contact_links:
  - name: "Q&A - GitHub Discussions"
    url: https://github.com/vietmap-company/vietmap_flutter_gl/discussions/categories/q-a
    about: "If you have a question about using VietmapGL on Flutter"
  - name: "Join on Slack"
    url: https://slack.openstreetmap.us/
    about: "Join #maplibre-flutter on the OpenStreetMap Slack"
